//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public int BookingID { get; set; }
        public int VehicleID { get; set; }
        public int UserID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public decimal TotalCost { get; set; }
        public int StatusID { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<int> InsuranceID { get; set; }
        public Nullable<decimal> ActualCost { get; set; }

        public bool HasReview
        {
            get
            {
                using (var context = new DBEntities())
                {
                    return context.Reviews.Any(r => r.UserID == UserID && r.VehicleID == VehicleID);
                }
            }
        }

        public bool IsStarted
        {
            get
            {
                return StartDate.Date <= DateTime.Today;
            }
        }

        public virtual Vehicle Vehicle { get; set; }
        public virtual Insurance Insurance { get; set; }
        public virtual User User { get; set; }
        public virtual BookingStatus BookingStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
