//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.IO;
    using System.Linq;
    using System.Windows.Media;
    using System.Windows.Media.Imaging;

    public partial class Vehicle : INotifyPropertyChanged
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.Bookings = new HashSet<Booking>();
            this.Reviews = new HashSet<Review>();
            this.VehicleImages = new HashSet<VehicleImage>();
        }

        public int VehicleID { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }

        // VehicleImage is now deprecated but kept for backward compatibility
        // This property will be gradually phased out as we move to VehicleImages collection
        private byte[] _vehicleImage;
        public byte[] VehicleImage
        {
            get => _vehicleImage;
            set
            {
                _vehicleImage = value;
                _vehicleImageSource = null;
                OnPropertyChanged(nameof(VehicleImage));
                OnPropertyChanged(nameof(VehicleImageSource));
            }
        }

        public int Year { get; set; }
        public string LicensePlate { get; set; }
        public Nullable<int> VehicleCategoryID { get; set; }
        public decimal DailyRate { get; set; }
        public bool Available { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<decimal> AvgRating { get; set; }

        public string FullName
        {
            get { return $"{Make} {Model} {Year}"; }
        }

        private ImageSource _vehicleImageSource;
        public ImageSource VehicleImageSource
        {
            get
            {
                // First try to get image from VehicleImages collection
                if (_vehicleImageSource == null && VehicleImages != null && VehicleImages.Count > 0)
                {
                    var firstImage = VehicleImages.FirstOrDefault();
                    if (firstImage != null && !string.IsNullOrEmpty(firstImage.ImagePath))
                    {
                        try
                        {
                            _vehicleImageSource = new BitmapImage(new Uri(firstImage.ImagePath));
                        }
                        catch
                        {
                            // If there's an error loading from URL, fall back to placeholder
                            _vehicleImageSource = new BitmapImage(new Uri("pack://application:,,,/Resources/Images/car_placeholder.png"));
                        }
                    }
                }
                // Fall back to legacy VehicleImage if needed
                else if (_vehicleImageSource == null && VehicleImage != null && VehicleImage.Length > 0)
                {
                    try
                    {
                        using (var stream = new System.IO.MemoryStream(VehicleImage))
                        {
                            var bitmapImage = new BitmapImage();
                            bitmapImage.BeginInit();
                            bitmapImage.CacheOption = BitmapCacheOption.OnLoad;
                            bitmapImage.StreamSource = stream;
                            bitmapImage.EndInit();
                            bitmapImage.Freeze();
                            _vehicleImageSource = bitmapImage;
                        }
                    }
                    catch
                    {
                        // If there's an error with the binary data, use placeholder
                        _vehicleImageSource = new BitmapImage(new Uri("pack://application:,,,/Resources/Images/car_placeholder.png"));
                    }
                }
                // Use placeholder if no images available
                else if (_vehicleImageSource == null)
                {
                    _vehicleImageSource = new BitmapImage(new Uri("pack://application:,,,/Resources/Images/car_placeholder.png"));
                }

                return _vehicleImageSource;
            }
        }

        public event PropertyChangedEventHandler PropertyChanged;
        public void OnPropertyChanged(string propertyName)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
        public virtual VehicleCategory VehicleCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleImage> VehicleImages { get; set; }
    }

}
