// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPI.EF;

public partial class BookingStatus
{
    public int BookingStatusID { get; set; }

    public string BookingStatus1 { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();
}