// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPI.EF;

public partial class Payment
{
    public int PaymentID { get; set; }

    public int? BookingID { get; set; }

    public decimal Amount { get; set; }

    public int? PaymentMethodID { get; set; }

    public int? PaymentStatusID { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Booking Booking { get; set; }

    public virtual PaymentMethod PaymentMethod { get; set; }

    public virtual PaymentStatus PaymentStatus { get; set; }
}