// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPI.EF;

public partial class Review
{
    public int ReviewID { get; set; }

    public int? VehicleID { get; set; }

    public int? UserID { get; set; }

    public int Rating { get; set; }

    public string Comment { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual User User { get; set; }

    public virtual Vehicle Vehicle { get; set; }
}