// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebAPI.EF;

public partial class Vehicle
{
    public int VehicleID { get; set; }

    public string Make { get; set; }

    public string Model { get; set; }

    public byte[] VehicleImage { get; set; }

    public int Year { get; set; }

    public string LicensePlate { get; set; }

    public string VIN { get; set; }

    public int? VehicleCategoryID { get; set; }

    public decimal DailyRate { get; set; }

    public bool? Available { get; set; }

    public DateTime? CreatedAt { get; set; }

    public decimal? AvgRating { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    public virtual VehicleCategory VehicleCategory { get; set; }
}