// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplicationAPI.EF;

public partial class Booking
{
    public int BookingID { get; set; }

    public int? VehicleID { get; set; }

    public int? UserID { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public DateTime? ReturnDate { get; set; }

    public decimal TotalCost { get; set; }

    public int StatusID { get; set; }

    public DateTime? CreatedAt { get; set; }

    public int? InsuranceID { get; set; }

    public decimal? ActualCost { get; set; }

    public virtual Insurance Insurance { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual BookingStatus Status { get; set; }

    public virtual User User { get; set; }

    public virtual Vehicle Vehicle { get; set; }
}