// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplicationAPI.EF;

public partial class Insurance
{
    public int InsuranceID { get; set; }

    public string InsuranceName { get; set; }

    public string InsuranceDetails { get; set; }

    public decimal? InsurancePrice { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();
}