// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplicationAPI.EF;

public partial class VehicleCategory
{
    public int VehicleCategoryID { get; set; }

    public string VehicleCategory1 { get; set; }

    public virtual ICollection<Vehicle> Vehicles { get; set; } = new List<Vehicle>();
}